theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: title

# 对你自己的简洁描述
description: description

# 照片地址
logo: life_pic.jpg

# 你的名字
name: Zeyu Zhang(张泽宇)

# 你的联系方式
phone: 18373155515

# 你的邮箱
email: 15139819779@163.com
          aceblue666@gmail.com
# 你目前的住址
address: Guangzhou(广州)

# 你毕业院校
# school: school

# 你的专业
# profession: profession

# 你的学位
# degree: degree

# 你获得过的证书或奖励
# credential: credential
